/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorModeSwitch: typeof import('./src/components/ColorModeSwitch.vue')['default']
    Fallback: typeof import('./src/components/fallback.vue')['default']
    Loading: typeof import('./src/components/loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunningStatus: typeof import('./src/components/RunningStatus.vue')['default']
    UAlert: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UColorModeButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue')['default']
    UForm: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    URadioGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue')['default']
    UTable: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTimeline: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue')['default']
  }
}

// For TSX support
declare global {
  const ColorModeSwitch: typeof import('./src/components/ColorModeSwitch.vue')['default']
  const Fallback: typeof import('./src/components/fallback.vue')['default']
  const Loading: typeof import('./src/components/loading.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const RunningStatus: typeof import('./src/components/RunningStatus.vue')['default']
  const UAlert: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
  const UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  const UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
  const UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
  const UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
  const UCheckbox: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
  const UColorModeButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue')['default']
  const UForm: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
  const UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
  const UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
  const UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
  const URadioGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue')['default']
  const UTable: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
  const UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
  const UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  const UTimeline: typeof import('./node_modules/.pnpm/@nuxt+ui@4.7.1_@internation_4c1cb3b636f7d584f1cf2f281d8e47d4/node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue')['default']
}